baseURL = "https://Torebarr85.github.io/notes/"
languageCode = "en-us"
title = "Notes"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true

[permalinks]
  posts = "/:sections/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name = "AWS"
    url  = "/tags/aws/"
    weight = 10

  [[menu.main]]
    name = "Docker"
    url  = "/tags/docker/"
    weight = 20

  [[menu.main]]
    name = "Kubernetes"
    url  = "/tags/kubernetes/"
    weight = 30

  [[menu.main]]
    name = "Linux"
    url  = "/tags/linux/"
    weight = 40

  [[menu.main]]
    name = "Networking"
    url  = "/tags/networking/"
    weight = 50

  [[menu.main]]
    name = "Nginx"
    url  = "/tags/nginx/"
    weight = 60

  [[menu.main]]
    name = "Virtualization"
    url  = "/tags/virtualization/"
    weight = 70

  [[menu.main]]
    name = "Webserver"
    url  = "/tags/webserver/"
    weight = 80

  [[menu.main]]
    name = "All topics"
    url  = "/tags/"
    weight = 99
