baseURL = "https://Torebarr85.github.io/notes/"
languageCode = "en-us"
title = "Notes"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true

[permalinks]
  aws = "/aws/:slug/"
  docker = "/docker/:slug/"
  kubernetes = "/kubernetes/:slug/"
  linux = "/linux/:slug/"
  networking = "/networking/:slug/"
  nginx = "/nginx/:slug/"
  virtualization = "/virtualization/:slug/"
  webserver = "/webserver/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true




[menu]
  [[menu.main]]
    name = "AWS"
    pageRef = "tags/aws"
    weight = 10

  [[menu.main]]
    name = "Docker"
    pageRef = "tags/docker"
    weight = 20

  [[menu.main]]
    name = "Kubernetes"
    pageRef = "tags/kubernetes"
    weight = 30

  [[menu.main]]
    name = "Linux"
    pageRef = "tags/linux"
    weight = 40

  [[menu.main]]
    name = "Networking"
    pageRef = "tags/networking"
    weight = 50

  [[menu.main]]
    name = "Nginx"
    pageRef = "tags/nginx"
    weight = 60

  [[menu.main]]
    name = "Virtualization"
    pageRef = "tags/virtualization"
    weight = 70

  [[menu.main]]
    name = "Webserver"
    pageRef = "tags/webserver"
    weight = 80

  [[menu.main]]
    name = "All topics"
    pageRef = "tags"
    weight = 99
